<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Common Dog & Cat Breed Dictionary
    |--------------------------------------------------------------------------
    | Used by BreedMaskerService to censor breed mentions in pet descriptions
    | for non-approved adopters. Ordered by length (longest first) to prevent
    | partial matches (e.g. "Maine Coon" before "Coon").
    |
    */

    'dogs' => [
        // Multi-word breeds first (longest match priority)
        'German Shepherd',
        'Golden Retriever',
        'Labrador Retriever',
        'Siberian Husky',
        'Border Collie',
        'Australian Shepherd',
        'Great Dane',
        'Saint Bernard',
        'Bull Terrier',
        'Cocker Spaniel',
        'Springer Spaniel',
        'Staffordshire Bull Terrier',
        'Doberman Pinscher',
        'Miniature Schnauzer',
        'Jack Russell Terrier',
        'Yorkshire Terrier',
        'Cavalier King Charles Spaniel',
        'Shih Tzu',
        'Bichon Frise',
        'Basset Hound',
        'French Bulldog',
        'English Bulldog',
        'Boston Terrier',
        'West Highland Terrier',
        'Shetland Sheepdog',
        'Belgian Malinois',
        // Single-word breeds
        'Labrador',
        'Retriever',
        'Poodle',
        'Bulldog',
        'Beagle',
        'Rottweiler',
        'Chihuahua',
        'Dachshund',
        'Pomeranian',
        'Maltese',
        'Pug',
        'Boxer',
        'Dalmatian',
        'Weimaraner',
        'Samoyed',
        'Akita',
        'Mastiff',
        'Greyhound',
        'Whippet',
        'Vizsla',
        'Bloodhound',
        'Doberman',
        'Schnauzer',
        'Collie',
        'Spitz',
        'Pointer',
        'Setter',
        'Spaniel',
        'Terrier',
        'Shepherd',
        // Philippine-local breeds
        'Aspin',
        'Askal',
        'Irong Bisaya',
    ],

    'cats' => [
        // Multi-word breeds first
        'Maine Coon',
        'British Shorthair',
        'British Longhair',
        'American Shorthair',
        'American Longhair',
        'Scottish Fold',
        'Devon Rex',
        'Cornish Rex',
        'Norwegian Forest Cat',
        'Turkish Angora',
        'Turkish Van',
        'Oriental Shorthair',
        'Oriental Longhair',
        'Selkirk Rex',
        'La Perm',
        // Single-word breeds
        'Birman',
        'Siamese',
        'Persian',
        'Ragdoll',
        'Bengal',
        'Sphynx',
        'Abyssinian',
        'Burmese',
        'Tonkinese',
        'Manx',
        'Savannah',
        'Bombay',
        'Chartreux',
        'Balinese',
        'Himalayan',
        'Munchkin',
        'Singapura',
        'Snowshoe',
        'Ragamuffin',
        'Pixiebob',
        'Ocicat',
        'Somali',
        'Javanese',
        'Cymric',
        // Philippine-local breeds
        'Puspin',
        'Puspusa',
        'Bantay',
    ],
];
